### ISSUE TITLE
Move to using yarn?

### ISSUE THREAD

**Issue by JuanCaicedo** [jamesshore/quixote#48] opened 2017-04-18 02:35 UTC
Some discussion about using yarn:

- https://github.com/jamesshore/quixote/issues/46#issuecomment-294649228
- https://github.com/jamesshore/quixote/issues/46#issuecomment-294651684

Seems like it's not a big deal at the moment, but I thought I'd make an issue for discussion

**Comment by ioneyed** [comment] 2017-05-06 20:25
Yarn would only be needed if you intend on keeping the non specific version in the package json. If you want to "Lock" the version just use the absolute version and plan in your build process or contribution process to make people update versions to the next non breaking specific.

https://docs.npmjs.com/files/package.json#dependencies

**Comment by jamesshore** [comment] 2017-05-07 02:54
The current approach to dependencies is working as intended. Closing this for now.

**Closed by jamesshore** 2017-05-07 02:54 UTC
Labels: discussion
